### ISSUE TITLE
ChannelRead does not fire in EchoServerHandler

### ISSUE THREAD

**Issue by mortezasoft** [Azure/DotNetty#127]
I am using your Echo.Server example project and a simple .NET code to call the server as follow:

TcpClient client = new TcpClient();
client.Connect("IP HERE", "PORT HERE");
var data = Encoding.UTF8.GetBytes("Hello world");
Stream stm = client.GetStream();
stm.Write(data, 0, data.Length);
byte[] readBytes = new byte[100];
stm.Read(readBytes, 0, readBytes.Length);
stm.Dispose();
client.Close(); 

But when I send the request, only ChannelReadComplete fires in SeverHandler and not ChannelRead!
Is it an issue or I am missing something?

**Comment by mortezasoft** [comment]
I removed the line below from the server configuration and it started working:

 pipeline.AddLast(new LengthFieldBasedFrameDecoder(ushort.MaxValue, 0, 2, 0, 2));

**Comment by nayato** [comment]
@mortezasoft, LengthFieldBasedFrameDecoder expects length prefix of defined length (see XML-DOC comments on the class/ctor). TCP is stream based protocol. You might send 10 bytes and receive 10 packets of 1 byte on the other end. The decoder in question (and matching LengthFieldPrepender) makes sure messages arrive to higher level handlers in tact. In order to make stream-based implementation work with it you'd have to write two bytes in Big-Endian defining length of the following message (`data.Length`, e.g. `0x00, 0x0B` for 11 bytes of "Hello world").
