### ISSUE TITLE
Making changes to the Dotnetty MQTT Codec and make it work across the protocol gateway.

### ISSUE THREAD

**Issue by whizlingo** [Azure/DotNetty#128]
I am making some changes into the Dotnetty MQTT Codec library to meet some custom requirements. It seems that the Azure Device client library also has dependency on the Nuget package for MQTT Codec and expects following version - 
`DotNetty.Codecs.Mqtt, Version=0.3.1.0, Culture=neutral, PublicKeyToken=e7a0210a354f294a.`

Is there a way i can sign the MQTT Codec library that i have using the same cert/key to make it work for Azure Device Client library as well ?. I see a cert in the shared folder, Is it the one used for signing the projects ?

**Comment by nayato** [comment]
there is no way to produce assembly with the same key and you cannot redirect the reference to an assembly with different publickeytoken. What kind of changes are you making that it would make sense to put them in MQTT codec? would it make sense to generalize those and integrate in DotNetty itself? Otherwise, only option I see right now is to build Azure Device Client along with your custom DotNetty build.
