### ISSUE TITLE
Backlog?

### ISSUE THREAD

**Issue by rogeralsing** [Azure/DotNetty#31]
I was talking to @Aaronontheweb earlier and started looking at `MultithreadEventExecutorGroup` and base types as per his request.
Can I go ahead and port those parts?

Are there any plans to make a more detailed backlog?
I think that would greatly improve the number of contribs you see here

**Comment by adamhathcock** [comment]
I'd also be interested in seeing a backlog and motivations for this project to see where it's headed.

My token request/interest is DNX/Net Core support.

**Comment by nayato** [comment]
@rogeralsing, yes, we need a better backlog.. I'll add a few most wanted items like HTTP and HTTP 2 codecs port, libuv-based channel / event loop implementation. These are really big items and it isn't easy to port them in one go. I'm working myself on an honest buffer pool port and there are enough head-scratching details
.
Execution model is rather hard to port 1-1 because often times you would find .NET having different concepts + I believe JDK license won't allow porting Java parts easily. Have you seen current implementation? It is close enough to that of `MultithreadEventLoopGroup` and `SingleThreadEventExecutor`. We did away with EventLoopGroup inheriting from EventLoop not to overload the concept (it's rarely used and is easy to achieve with getNext()). I'd suggest to discuss it further in a separate issue or on gitter.
