### ISSUE TITLE
Utility type mapping

### ISSUE THREAD

**Issue by rogeralsing** [Azure/DotNetty#32]
Are these types already mapped to something in .NET?
We have AtomicInteger in Akka.NET so we could bring that right over if needed(?)

```
Set<T>
AtomicInteger
Callable<T>
TimeUnit
```

**Comment by nayato** [comment]
Hey Roger, I would say:
- `ISet<T>` but it's somewhat harder to implement
- `Interlocked` is the only close thing and yes, for porting reasons it should be fine to intro AtomicInteger.
- `Func<T>` is the closest but it's a delegate which restricts the number of scenarios where it can be used (notice, we introduced IRunnable instead of relying on Action).
- `TimeSpan` because `TimeUnit` is usually used in conjunction with actual value.

**Comment by nayato** [comment]
I checked AtomicCounter in Akka.NET. I don't think it needs to have an interface counterpart and can be marked as sealed.
