### ISSUE TITLE
Bootstrap.ConnectAsync deadlock in asp.net(not core)

### ISSUE THREAD

**Issue by Coldairarrow** [Azure/DotNetty#463]
var clientChannel = bootstrap.ConnectAsync($"127.0.0.1:8888".ToIPEndPoint()).Result;
this will deadlock  in asp.net(not core)
but it is well in Console
this is because await async method in asp.net will deadlock
I use Task<T>.Result in replaese await keyword Solved this problem 
so please solve it

last:is there any negative effects in my way ?

**Comment by caozhiyuan** [comment]
it's not netty problem , because  asp.net synchronizationcontext , but console has no synchronizationcontext ,  just call Result is not safe. you can use getawait getresult (also will dead lock in some case ) or use microsoft lib RunSync [method](https://stackoverflow.com/questions/5095183/how-would-i-run-an-async-taskt-method-synchronously)

**Comment by Coldairarrow** [comment]
thanks for you answer and Solved my problem very much
